### ISSUE TITLE
Xiaomi Mi Flora BLE battery level missing 

### ISSUE THREAD

**Issue by eddKv** [AlCalzone/ioBroker.ble#515] opened 2021-01-07 20:41 UTC
**Describe the bug**  
Normally the battery status should be shown as a value. This data is very helpful to know when to change the battery.

**To Reproduce**  
Connect Flower Care Sensor. 4 sensor data were discovered and listed. Missing is the battery level and firmware.

**Expected behavior**  
The battery level and the firmware should be shown in the objects list.

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/76760245/103942490-c4627900-5130-11eb-9a8d-e097a341ad77.png)

**Versions:**  
BLE 0.12.0

**Additional context**  
There is another similar JS on GitHub, which helps: https://github.com/ChrisScheffler/miflora

**Comment by AlCalzone** [comment] 2021-01-07 21:49
AFAIK these are the only values the device sends by default, or are you using the custom firmware?

**Comment by eddKv** [comment] 2021-01-08 16:09
No, I'm using the default firmware. But the battery status must be visible somehow, because the Flower Care app alerts on low battery, so any trigger or value must be there. It seems that the battery level must be read in a different way.

**Comment by AlCalzone** [comment] 2021-01-08 16:41
> It seems that the battery level must be read in a different way.

Yep!

Duplicate of: #106

**Closed** 2021-01-08 16:41 UTC
