### ISSUE TITLE
Feature Request New Xiaomi Mijia Bluetooth Thermometer

### ISSUE THREAD

**Issue by FabianHM** [AlCalzone/ioBroker.ble#404] opened 2020-05-22 16:08 UTC
Hello, I have the new Xiaomi Mijia Bluetooth thermometer.
https://de.aliexpress.com/item/4000713871310.html?spm=2114.13010708.0.0.58ea4c4dVFo7Ys. 
The device is found as follows, but only RSSI is received:

![thermometer](https://user-images.githubusercontent.com/26110738/82687161-3bf19f80-9c57-11ea-8015-217f7be68df5.JPG)

It would be great if the existing plugin could also support this device.

Thank you in advance for your support.
greetings
Fabian

**Comment by AlCalzone** [comment] 2020-05-22 16:13
duplicate of #352 

The packet in your screenshot contains no data, only the MAC address, so there's nothing the adapter can do with that.

**Closed by AlCalzone** 2020-05-22 16:13 UTC
