### ISSUE TITLE
Compiled against a different Node.js version using NOD

### ISSUE THREAD

**Issue by daniel-lo** [AlCalzone/ioBroker.ble#394] opened 2020-04-27 20:17 UTC
I have problems activating the adapter .. could somebody help?

ble.0 | 2020-04-27 22:15:41.122 | error | (8299)  unhandled promise rejection: Error: The module  '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node' was compiled against a different Node.js version using NOD
-- | -- | -- | --
ble.0 | 2020-04-27 22:15:41.121 | error | (8299) Error: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 67. This ver
ble.0 | 2020-04-27 22:15:41.120 | error | (8299) uncaught exception: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node' was compiled against a different Node.js version using NODE_MODULE_VERSION

**Comment by daniel-lo** [comment] 2020-04-27 20:22
oh .. there's more ...

ble.0 | 2020-04-27 20:21:12.257 | error | the module (for instance, using `npm rebuild` or `npm install`).
-- | -- | -- | --
ble.0 | 2020-04-27 20:21:12.257 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ble.0 | 2020-04-27 20:21:12.257 | error | NODE_MODULE_VERSION 67. This version of Node.js requires
ble.0 | 2020-04-27 20:21:12.257 | error | was compiled against a different Node.js version using
ble.0 | 2020-04-27 20:21:12.257 | error | (15024) unhandled promise rejection: Error: The module  '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'
ble.0 | 2020-04-27 20:21:12.255 | error | at Function.Module._load (internal/modules/cjs/loader.js:899:14)
ble.0 | 2020-04-27 20:21:12.255 | error | at Module.load (internal/modules/cjs/loader.js:1000:32)
ble.0 | 2020-04-27 20:21:12.255 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
ble.0 | 2020-04-27 20:21:12.255 | error | at Module._compile (internal/modules/cjs/loader.js:1156:30)
ble.0 | 2020-04-27 20:21:12.255 | error | at Object.<anonymous> (/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
ble.0 | 2020-04-27 20:21:12.255 | error | at require (internal/modules/cjs/helpers.js:77:18)
ble.0 | 2020-04-27 20:21:12.255 | error | at Module.require (internal/modules/cjs/loader.js:1042:19)
ble.0 | 2020-04-27 20:21:12.255 | error | at Function.Module._load (internal/modules/cjs/loader.js:899:14)
ble.0 | 2020-04-27 20:21:12.255 | error | at Module.load (internal/modules/cjs/loader.js:1000:32)
ble.0 | 2020-04-27 20:21:12.255 | error | at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
ble.0 | 2020-04-27 20:21:12.255 | error | the module (for instance, using `npm rebuild` or `npm install`).
ble.0 | 2020-04-27 20:21:12.255 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ble.0 | 2020-04-27 20:21:12.255 | error | NODE_MODULE_VERSION 67. This version of Node.js requires
ble.0 | 2020-04-27 20:21:12.255 | error | was compiled against a different Node.js version using
ble.0 | 2020-04-27 20:21:12.255 | error | (15024) Error: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'
ble.0 | 2020-04-27 20:21:12.253 | error | the module (for instance, using `npm rebuild` or `npm install`).
ble.0 | 2020-04-27 20:21:12.253 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ble.0 | 2020-04-27 20:21:12.253 | error | NODE_MODULE_VERSION 67. This version of Node.js requires
ble.0 | 2020-04-27 20:21:12.253 | error | was compiled against a different Node.js version using
ble.0 | 2020-04-27 20:21:12.253 | error | (15024) uncaught exception: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'

**Comment by AlCalzone** [comment] 2020-04-28 06:19
After you update Node.js, you need to do two things:
1. run the fixer
2. rebuild all native dependencies (like bluetooth-hci-socket). If you are on JS-Controller 3.x, it will do that for you automatically. If not, run this:
```
cd /opt/iobroker/node_modules/iobroker.ble
npm i --production
```

**Comment by daniel-lo** [comment] 2020-04-28 06:39
thanks .. it's yellow now .. connected with BLE is red

**Comment by AlCalzone** [comment] 2020-04-28 06:41
Did you run the fixer?

**Comment by daniel-lo** [comment] 2020-04-28 07:17
"unknown"

**Comment by daniel-lo** [comment] 2020-04-28 07:18
hciconfig -a

hci0:   Type: Primary  Bus: USB
        BD Address: 34:13:E8:1D:DB:2E  ACL MTU: 1021:5  SCO MTU: 96:6
        UP RUNNING
        RX bytes:1459 acl:0 sco:0 events:93 errors:0
        TX bytes:2863 acl:0 sco:0 commands:93 errors:0
        Features: 0xff 0xfe 0x0f 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH HOLD SNIFF
        Link mode: SLAVE ACCEPT
        Name: 'iobroker'
        Class: 0x000000
        Service Classes: Unspecified
        Device Class: Miscellaneous,
        HCI Version: 4.2 (0x8)  Revision: 0x1000
        LMP Version: 4.2 (0x8)  Subversion: 0x1000
        Manufacturer: Intel Corp. (2)

**Comment by AlCalzone** [comment] 2020-04-28 07:20
Did you run the fixer?

**Comment by daniel-lo** [comment] 2020-04-28 08:09
sure .. over and over again.

**Comment by AlCalzone** [comment] 2020-04-28 08:48
If the adapter worked before the update you might need to reboot.
Otherwise, I'm not sure what to do.

**Comment by daniel-lo** [comment] 2020-04-28 08:56
No .. it never worked for me .. I just switched form lxc container to vm because Proxmos has problems passing foward bluetooth to containers .. so in fact I just switched for your adapter ;-)

**Comment by AlCalzone** [comment] 2020-04-28 09:00
Then I'm guessing that the adapter cannot access your bluetooth hardware or it is not compatible (is it even Bluetooth Low Energy?) Sadly I don't have that much experience with the hardware/driver side. I'm just using a library for that and it works on my Raspberry ;)

**Comment by daniel-lo** [comment] 2020-04-28 09:04
I just tried radar2.0 adapter and mybe the output of the log sheds some light? I might ask there as well.


radar2.0 | 2020-04-28 11:02:58.936 | info | (928) radar2 set to scan every 20 seconds and printers every 720 minutes.
-- | -- | -- | --
radar2.0 | 2020-04-28 11:02:58.935 | info | (928) arp-scan will use the following interfaces: [ 'ens18' ]
radar2.0 | 2020-04-28 11:02:58.935 | info | (928) Remove name end for host names: .fritz.box
radar2.0 | 2020-04-28 11:02:58.934 | info | (928) use known IP list: []
radar2.0 | 2020-04-28 11:02:58.934 | info | (928) use known BT list: []
radar2.0 | 2020-04-28 11:02:58.934 | info | (928) radar2 set to flag items away if they are not seen for 2 minutes
radar2.0 | 2020-04-28 11:02:58.933 | warn | (928) node-bluetooth not found!
radar2.0 | 2020-04-28 11:02:58.932 | warn | (928)  Noble not available, Error: Error: The module  '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was  compiled against a different Node.js version usingNODE_MO
radar2.0 | 2020-04-28 11:02:58.852 | info | (928) Adapter disconnected and stopped with dostop(false) and callback(true)
radar2.0 | 2020-04-28 11:02:58.851 | error | (928) Error: bind EACCES 0.0.0.0:67     at dgram.js:339:20     at processTicksAndRejections (internal/process/task_queues.js:85:21)
radar2.0 | 2020-04-28 11:02:58.851 | error | (928) uncaught exception: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 11:02:58.778 | info | (928) net-ping not available! Will try to use normal ping!
radar2.0 | 2020-04-28 11:02:58.773 | info | (928) radar2 initialization started...
radar2.0 | 2020-04-28 11:02:58.764 | warn | (928)  adapter.objects.getObjectList is deprecated, and will be removed in the  future. Please use adapter.getObjectList/Async. Report this to  Developer!
radar2.0 | 2020-04-28 11:02:58.713 | info | (928) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v12.16.2, js-controller: 3.0.19
radar2.0 | 2020-04-28 09:02:27.327 | info | (32526) radar2 set to scan every 20 seconds and printers every 720 minutes.
radar2.0 | 2020-04-28 09:02:27.327 | info | (32526) arp-scan will use the following interfaces: [ 'ens18' ]
radar2.0 | 2020-04-28 09:02:27.326 | info | (32526) Remove name end for host names: .fritz.box
radar2.0 | 2020-04-28 09:02:27.326 | info | (32526) use known IP list: []
radar2.0 | 2020-04-28 09:02:27.325 | info | (32526) use known BT list: []
radar2.0 | 2020-04-28 09:02:27.325 | info | (32526) radar2 set to flag items away if they are not seen for 2 minutes
radar2.0 | 2020-04-28 09:02:27.325 | warn | (32526) node-bluetooth not found!
radar2.0 | 2020-04-28 09:02:27.323 | warn | (32526) Noble not available, Error: Error: The module  '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was  compiled against a different Node.js version usingNODE
radar2.0 | 2020-04-28 09:02:27.170 | info | (32526) Adapter disconnected and stopped with dostop(false) and callback(true)
radar2.0 | 2020-04-28 09:02:27.169 | error | at processTicksAndRejections (internal/process/task_queues.js:85:21)
radar2.0 | 2020-04-28 09:02:27.169 | error | at dgram.js:339:20
radar2.0 | 2020-04-28 09:02:27.169 | error | (32526) Error: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 09:02:27.168 | error | (32526) uncaught exception: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 09:02:27.093 | info | (32526) net-ping not available! Will try to use normal ping!
radar2.0 | 2020-04-28 09:02:27.084 | info | (32526) radar2 initialization started...
radar2.0 | 2020-04-28 09:02:27.074 | warn | (32526) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
radar2.0 | 2020-04-28 09:02:27.020 | info | (32526) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v12.16.2, js-controller: 3.0.19

**Comment by AlCalzone** [comment] 2020-04-28 09:22
> /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was compiled against a different Node.js version usingNODE_MO

This seems like you did not successfully recompile the library.
Try
```
cd /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket
npm i --production
```
and possibly
```
cd /opt/iobroker/node_modules/@abandonware/noble
npm i --production
```

However, `bind EACCES 0.0.0.0:67` leads me to believe that the fixer did not update the permissions of the Node.js binary. Try doing it manually
```
sudo setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw+eip' $(eval readlink -f `which node`)
```
(exactly like this, don't replace anything)

**Comment by daniel-lo** [comment] 2020-04-28 10:38
no change 


radar2.0 | 2020-04-28 10:37:11.199 | info | (10062) radar2 set to scan every 20 seconds and printers every 720 minutes.
-- | -- | -- | --
radar2.0 | 2020-04-28 10:37:11.199 | info | (10062) arp-scan will use the following interfaces: [ 'ens18' ]
radar2.0 | 2020-04-28 10:37:11.199 | info | (10062) Remove name end for host names: .fritz.box
radar2.0 | 2020-04-28 10:37:11.198 | info | (10062) use known IP list: [ '1.1.1.1' ]
radar2.0 | 2020-04-28 10:37:11.198 | info | (10062) use known BT list: [ '01:12:23:34:45:56' ]
radar2.0 | 2020-04-28 10:37:11.197 | info | (10062) radar2 set to flag items away if they are not seen for 2 minutes
radar2.0 | 2020-04-28 10:37:11.196 | warn | (10062) node-bluetooth not found!
radar2.0 | 2020-04-28 10:37:11.196 | info | (10062) found '@abandonware/noble'
radar2.0 | 2020-04-28 10:37:11.108 | info | (10062) Adapter disconnected and stopped with dostop(false) and callback(true)
radar2.0 | 2020-04-28 10:37:11.108 | error | at processTicksAndRejections (internal/process/task_queues.js:85:21)
radar2.0 | 2020-04-28 10:37:11.108 | error | at dgram.js:339:20
radar2.0 | 2020-04-28 10:37:11.108 | error | (10062) Error: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 10:37:11.107 | error | (10062) uncaught exception: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 10:37:11.039 | info | (10062) net-ping not available! Will try to use normal ping!
radar2.0 | 2020-04-28 10:37:11.034 | info | (10062) radar2 initialization started...
radar2.0 | 2020-04-28 10:37:11.023 | warn | (10062) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
radar2.0 | 2020-04-28 10:37:10.959 | info | (10062) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v12.16.2, js-controller: 3.0.19

**Comment by AlCalzone** [comment] 2020-04-28 11:58
I cannot speak for radar, although that is also using the `noble` module. Have you tried BLE after these changes?

**Comment by daniel-lo** [comment] 2020-04-28 12:08
sure .. the radar log was just in case it helps

**Comment by AlCalzone** [comment] 2020-04-28 13:57
So `driverState` is still `unknown`?

**Comment by daniel-lo** [comment] 2020-04-28 15:22
yes .. driverstate is unknown.

Log looks good:


ble.0 | 2020-04-28 15:22:01.893 | info | (31398) monitored services:
-- | -- | -- | --
ble.0 | 2020-04-28 15:22:01.892 | info | (31398) enabled plugins: _default
ble.0 | 2020-04-28 15:22:01.891 | info | (31398) loaded plugins: Xiaomi, mi-flora, ruuvi-tag, _default
ble.0 | 2020-04-28 15:22:01.784 | info | (31398) starting. Version 0.11.4 in /opt/iobroker/node_modules/iobroker.ble, node: v12.16.2, js-controller: 3.0.19
host.iobroker | 2020-04-28 15:22:00.335 | info | instance system.adapter.ble.0 started with pid 31398
host.iobroker | 2020-04-28 15:21:57.845 | info | instance system.adapter.ble.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
ble.0 | 2020-04-28 15:21:57.325 | info | (10279) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ble.0 | 2020-04-28 15:21:57.324 | info | (10279) terminating

**Comment by Apollon77** [comment] 2020-04-28 17:06
Do you handed the usb bluetooth device through to the VM?

**Comment by daniel-lo** [comment] 2020-04-28 17:12
It's the onboard BT of my NUC which I handed to the VM.
Above I posted my hciconfig output which I made in the iobroker VM shell.

**Comment by daniel-lo** [comment] 2020-04-29 06:39
@Apollon77 

maybe this gives you some insight:

Update js-controller from @3.0.19 to @3.0.20
NPM version: 6.14.4
npm install iobroker.js-controller@3.0.20 --loglevel error --unsafe-perm --prefi                                                                                               x "/opt/iobroker" (System call)
../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ de                                                                                               clared void
 void InitAll(Handle<Object> exports) {
              ^~~~~~
../src/linux/BluetoothSerialPort.cc:18:14: error: ‘Handle’ was not declared in t                                                                                               his scope
../src/linux/BluetoothSerialPort.cc:18:14: note: suggested alternative: ‘rand_r’
 void InitAll(Handle<Object> exports) {
              ^~~~~~
              rand_r
../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression be                                                                                               fore ‘>’ token
 void InitAll(Handle<Object> exports) {
                           ^
../src/linux/BluetoothSerialPort.cc:18:29: error: ‘exports’ was not declared in                                                                                                this scope
 void InitAll(Handle<Object> exports) {
                             ^~~~~~~
In file included from ../src/linux/BluetoothSerialPort.cc:12:0:
../src/linux/BluetoothSerialPort.cc:23:34: error: ‘InitAll’ was not declared in                                                                                                this scope
 NODE_MODULE(BluetoothSerialPort, InitAll)
                                  ^
/home/iobroker/.cache/node-gyp/12.16.2/include/node/node.h:608:36: note: in defi                                                                                               nition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro ‘NODE_MODU                                                                                               LE’
 NODE_MODULE(BluetoothSerialPort, InitAll)
 ^~~~~~~~~~~
make: *** [Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.                                                                                               o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_                                                                                               modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                               s.js:275:12)
gyp ERR! System Linux 4.15.0-96-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/n                                                                                               ode-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/iobroker/node_modules/node-bluetooth
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Starting node restart.js

**Comment by Apollon77** [comment] 2020-04-29 07:00
No sorry ... which adapter version do you have installed? And the error from js-controller update do not tell you if ble adater is the only place where bluetooth is used

**Comment by daniel-lo** [comment] 2020-04-29 07:08
0.11.4

**Comment by AlCalzone** [comment] 2020-04-29 09:08
Do you have multiple adapters using Bluetooth at the same time? That might be a problem.

**Comment by daniel-lo** [comment] 2020-04-29 13:13
nothing changes if I deactivate Radar2

**Comment by AlCalzone** [comment] 2020-04-29 13:18
Ok. Would you mind asking about the question in the forum? To be honest, I don't have any clue since my experience with troubleshooting BLE stops at installing the node modules which you already did.

**Comment by daniel-lo** [comment] 2020-04-29 13:27
will do

**Comment by daniel-lo** [comment] 2020-04-29 18:08
Amazing .. dot is yellow. But as soon as I enter:
"sudo hcitool lescan" in console it turns green.
It stays green until I restart the adapter.

And the command does list BT-Devices in the VM .. so much works .. seems to be only a small missing link.

Any idea that comes up?

**Comment by AlCalzone** [comment] 2020-04-29 19:40
You could have some luck with the forum search. I'm sure I've read that once.

**Comment by daniel-lo** [comment] 2020-04-29 20:48
sudo hcitool -i hci0 lescan .. is also a command that also has the mentioned effect .. just for the sake of completeness. I also found this old screenshot of radar .. where you could switch from noble to hcitool .. interesting. I read throught he forum .. but found no fix .. will continue to search.

![radar2config](https://user-images.githubusercontent.com/4311558/80645488-7c506a00-8a6b-11ea-8efa-0a5cf3de8a9c.png)

**Comment by daniel-lo** [comment] 2020-04-30 06:04
green now:

daniel@iobroker:/opt/iobroker$ node -v
v10.20.1
daniel@iobroker:/opt/iobroker$ nodejs -v
v10.20.1
daniel@iobroker:/opt/iobroker$ npm -v
6.14.4

In fact there seems to be an problem with newer versions of node/nodejs.

**Comment by AlCalzone** [comment] 2020-05-02 09:26
I can confirm. On Node.js 14.0.0, the driverState stays `unknown` for me too.

**Comment by daniel-lo** [comment] 2020-05-02 10:20
thanks for escalating!

**Comment by AlCalzone** [comment] 2020-05-03 07:40
@daniel-lo I'm not sure what I should say...
![grafik](https://user-images.githubusercontent.com/17641229/80908662-f6117d80-8d21-11ea-81df-8d289ad435de.png)

I noticed I had forgotten myself to re-set the capabilities after the node upgrade.
```
sudo setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw+eip' $(eval readlink -f `which node`)
```
and restarting ioBroker did the job for me.

**Comment by daniel-lo** [comment] 2020-05-03 08:05
Hmm .. I do recall having entered something like that .. during my testing to no avail. I am reluctant to update node and try again .. since now everything runs smoothly.

**Comment by AlCalzone** [comment] 2020-05-22 06:30
In the upstream issue it is also said that it is an issue of insufficient permissions. Since you don't plan on upgrading, I'm going to close this.
Feel free to reopen if the issue persists after updating node and running the fixer.

**Closed by AlCalzone** 2020-05-22 06:30 UTC
